# Generated by Django 3.0.5 on 2020-04-26 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgdesc', '0002_auto_20200424_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgdescdb',
            old_name='caption',
            new_name='caption_en',
        ),
    ]
