# Generated by Django 3.0.5 on 2020-04-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgdesc', '0004_imgdescdb_caption_ko'),
    ]

    operations = [
        migrations.AddField(
            model_name='imgdescdb',
            name='audio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
