# Generated by Django 3.0.5 on 2020-04-26 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgdesc', '0005_imgdescdb_audio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imgdescdb',
            old_name='audio',
            new_name='audio_url',
        ),
    ]
