# Generated by Django 3.0.5 on 2020-04-26 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgdesc', '0007_auto_20200427_0221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imgdescdb',
            name='audio',
        ),
        migrations.AddField(
            model_name='imgdescdb',
            name='audio_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imgdescdb',
            name='caption_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='imgdescdb',
            name='caption_ko',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
